site_name: 无忌
site_url: https://Hujiko02.github.io
site_author: 无忌
site_description: 无忌的个人网站

theme:
  name: material
  # 语言设置为中文
  language: zh
  # 配色方案（可切换明暗模式）
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: 深色模式

  features:
    - navigation.instant # 即时页面加载
    - navigation.tabs # 顶部标签页导航
    - navigation.indexes # 让分区标题本身可点击（index.md 当分区概览页）
    - navigation.top # 返回顶部按钮
    - navigation.tracking # 地址栏跟随锚点
    - toc.follow # 右侧目录跟随滚动高亮


nav:
  - 首页: index.md
  - 教程:
    - tutorial/index.md
    - Latex入门教程: tutorial/latex.md
    - Markdown入门教程: tutorial/markdown.md
    - Markdown测试: tutorial/markdown_test.md
    - Verilog入门教程: tutorial/verilog.md
    - Matplotlib入门教程: tutorial/matplotlib.md
  - 日记:
    - diary/index.md
    - 2026年: diary/2026.md
  - 关于我:
    - me/index.md
extra:
  social: 
    - name: 我的GitHub
      icon: fontawesome/brands/github
      link: https://github.com/Hujiko02
    - name: 我的Bilibili
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2058282898
   
# Markdown 扩展
markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

# 数学公式支持
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css


